// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/sales/:saleId": {
    params: {
      "saleId": string;
    };
  };
  "/sales/:saleId/lots/:lotId": {
    params: {
      "saleId": string;
      "lotId": string;
    };
  };
  "/vehicles/:vehicleId": {
    params: {
      "vehicleId": string;
    };
  };
  "/api/vehicles/:vehicleId": {
    params: {
      "vehicleId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/sales/:saleId" | "/sales/:saleId/lots/:lotId" | "/vehicles/:vehicleId" | "/api/vehicles/:vehicleId";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/sales.$saleId.tsx": {
    id: "routes/sales.$saleId";
    page: "/sales/:saleId";
  };
  "routes/sales.$saleId.lots.$lotId.tsx": {
    id: "routes/sales.$saleId.lots.$lotId";
    page: "/sales/:saleId/lots/:lotId";
  };
  "routes/vehicles.$vehicleId.tsx": {
    id: "routes/vehicles.$vehicleId";
    page: "/vehicles/:vehicleId";
  };
  "routes/api.vehicles.$vehicleId.ts": {
    id: "routes/api.vehicles.$vehicleId";
    page: "/api/vehicles/:vehicleId";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/sales.$saleId": typeof import("./app/routes/sales.$saleId.tsx");
  "routes/sales.$saleId.lots.$lotId": typeof import("./app/routes/sales.$saleId.lots.$lotId.tsx");
  "routes/vehicles.$vehicleId": typeof import("./app/routes/vehicles.$vehicleId.tsx");
  "routes/api.vehicles.$vehicleId": typeof import("./app/routes/api.vehicles.$vehicleId.ts");
};